version: '3.8'

services:
  app:
    build:
      context: .
      target: builder
    image: job-search-optimizer-dev
    container_name: job-search-optimizer-app-dev
    command: pnpm dev
    ports:
      - '3000:3000'
      - '9229:9229' # Для отладки
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/job_search_optimizer
      - REDIS_URL=redis://cache:6379
      - LOG_LEVEL=debug
    depends_on:
      - db
      - cache
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    container_name: job-search-optimizer-db-dev
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=job_search_optimizer
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  cache:
    image: redis:7-alpine
    container_name: job-search-optimizer-cache-dev
    ports:
      - '6379:6379'
    command: redis-server --appendonly no --save ""
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data_dev:
    driver: local
